import React from "react";

const BlrMap = props => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="921px"
    height="921px"
    {...props}
  >
    <g>
      <rect
        x="0"
        y="0"
        width="920"
        height="920"
        fill="#ffffff"
        stroke="#000000"
      />
      <rect
        x="720"
        y="30"
        width="200"
        height="80"
        fill="#ffffff"
        stroke="#000000"
      />
      <rect
        x="720"
        y="140"
        width="200"
        height="160"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="370"
        y="0"
        width="80"
        height="80"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="450"
        y="0"
        width="80"
        height="80"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="530"
        y="0"
        width="80"
        height="80"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="610"
        y="0"
        width="80"
        height="80"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="480"
        y="430"
        width="200"
        height="30"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="480"
        y="400"
        width="200"
        height="30"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="480"
        y="355"
        width="200"
        height="30"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="480"
        y="325"
        width="200"
        height="30"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="480"
        y="270"
        width="200"
        height="30"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="480"
        y="240"
        width="200"
        height="30"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="480"
        y="175"
        width="200"
        height="30"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="480"
        y="145"
        width="200"
        height="30"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="480"
        y="100"
        width="200"
        height="30"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="240"
        y="850"
        width="195"
        height="30"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="240"
        y="820"
        width="195"
        height="30"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="240"
        y="770"
        width="195"
        height="30"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="240"
        y="740"
        width="195"
        height="30"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="240"
        y="680"
        width="195"
        height="30"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="240"
        y="650"
        width="195"
        height="30"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="240"
        y="595"
        width="195"
        height="30"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="240"
        y="565"
        width="195"
        height="30"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="240"
        y="520"
        width="195"
        height="30"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="240"
        y="430"
        width="195"
        height="30"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="240"
        y="400"
        width="195"
        height="30"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="240"
        y="345"
        width="195"
        height="30"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="240"
        y="315"
        width="195"
        height="30"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="240"
        y="270"
        width="195"
        height="30"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="280"
        y="175"
        width="155"
        height="30"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="280"
        y="145"
        width="155"
        height="30"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="280"
        y="100"
        width="155"
        height="30"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="240"
        y="240"
        width="195"
        height="30"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="720"
        y="140"
        width="30"
        height="160"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="750"
        y="140"
        width="30"
        height="160"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="780"
        y="140"
        width="30"
        height="160"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="810"
        y="140"
        width="30"
        height="160"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="840"
        y="140"
        width="30"
        height="160"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="870"
        y="140"
        width="30"
        height="160"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="720"
        y="30"
        width="30"
        height="80"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="750"
        y="30"
        width="30"
        height="80"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="780"
        y="30"
        width="30"
        height="80"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="810"
        y="30"
        width="30"
        height="80"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="840"
        y="30"
        width="30"
        height="80"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="870"
        y="30"
        width="30"
        height="80"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="210"
        y="175"
        width="30"
        height="160"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="180"
        y="175"
        width="30"
        height="160"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="150"
        y="175"
        width="30"
        height="160"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="120"
        y="175"
        width="30"
        height="160"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="90"
        y="175"
        width="30"
        height="160"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="210"
        y="30"
        width="30"
        height="110"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="180"
        y="30"
        width="30"
        height="110"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="150"
        y="30"
        width="30"
        height="110"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="120"
        y="30"
        width="30"
        height="110"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
      <rect
        x="90"
        y="30"
        width="30"
        height="110"
        fill="#ffffff"
        stroke="#000000"
        pointer-events="none"
      />
    </g>
    <g>{props.children}</g>
  </svg>
);

export default BlrMap;
